### ISSUE TITLE
Return intersection type from Generator::getMock()

### ISSUE THREAD

**Issue by Stadly** [phpstan/phpstan-phpunit#32] opened 2018-12-10 06:39 UTC
The easiest way to create mock objects outside of a test case is through `PHPUnit\Framework\MockObject\Generator::getMock()`. This method does not return intersection types, like `PHPUnit\Framework\MockObject\MockBuilder::getMock()` and `PHPUnit\Framework\TestCase::createMock()` does.

Example:
```php
interface A {}

function foo(): A
{
    $generator = new PHPUnit\Framework\MockObject\Generator();
    return $generator->getMock(A::class);
}
```

```
 ------ -------------------------------------------------------------------------
  Line   test.php
 ------ -------------------------------------------------------------------------
  5      Function foo() should return A but returns
         PHPUnit\Framework\MockObject\MockObject.
 ------ -------------------------------------------------------------------------
```

**Comment by k00ni** [comment] 2020-08-05 13:26
I have the same problem here. When using mocks in PHPUnit like

> $this->getMockBuilder(EntityManagerInterface::class)->disableOriginalConstructor()->getMock();

PHPStan complains like

> Parameter #1 $entityManager of class App\Security\LoginFormAuthenticator constructor expects Doctrine\ORM\EntityManagerInterface, PHPUnit\Framework\MockObject\MockObject given.

I am not sure how to tell PHPStan that `getMock` will in fact return an object of that type in this instance.

**Comment by ondrejmirtes** [comment] 2020-08-05 13:34
@k00ni Just tried your problem and couldn't reproduce it. This works without a problem:

```php
<?php

class Foo extends \PHPUnit\Framework\TestCase
{

	public function testBlabla(): void
	{
		$mock = $this->getMockBuilder(\stdClass::class)->disableOriginalConstructor()->getMock();
		$this->doFoo($mock);
	}

	private function doFoo(\stdClass  $stdClass): void
	{

	}

}
```

No errors on max level.

In order to help you, please state:

* Your version of phpstan/phpstan, phpstan/phpstan-phpunit and phpunit/phpunit
* Your phpstan.neon

**Comment by ondrejmirtes** [comment] 2020-08-05 13:37
@Stadly You can solve your problem by adding custom stub files https://phpstan.org/user-guide/stub-files to your project, or by contributing [generic annotations](https://phpstan.org/blog/generics-in-php-using-phpdocs) to PHPUnit itself. I don't plan to address it in phpstan/phpstan-phpunit, because the class in PHPUnit is marked as `@internal` and shouldn't be really used outside of the project.

**Closed by ondrejmirtes** 2020-08-05 13:37 UTC

**Comment by k00ni** [comment] 2020-08-05 14:13
I wanted to provide a demo showing my problem, but after I set it up, I found out, that I actually ran PHPStan `0.11.x` together with phpstan-phpunit `0.11.x`. After upgrading to the latest 0.12.x such errors aren't mentioned anymore. I assume between these major versions this kind of "errors" got covered.

Anyway, thank you for the feedback.
