### ISSUE TITLE
prophesize deprecation error when using traits

### ISSUE THREAD

**Issue by Fabex** [phpstan/phpstan-phpunit#145] opened 2022-10-31 13:30 UTC
Hi, 
I don't know if it's the right repo, but since the last phpunit/phpunit version (9.5.26)
even if we use the `Prophecy\PhpUnit\ProphecyTrait`, to use the `prophesize`, phpstan raise an error about
```
Call to deprecated method prophesize() of class Class\Name:  
         https://github.com/sebastianbergmann/phpunit/issues/4141
```

This is because in [9.5.26](https://github.com/sebastianbergmann/phpunit/commit/c9da1dcac1a38653b0fd7a186e7a1abdc713eb3d), phpunit maintainers add a deprecation docbloc.

And after some search phpstan use reflection to read the docbloc for deprecation, and so like our tests extends `TestCase`, even if we use the Traits, phpstan don't follow the traits but the inheritance.

I hope my issue is clear enough, and you could fix this issue.

**Comment by ondrejmirtes** [comment] 2022-10-31 13:31
Duplicate of https://github.com/phpstan/phpstan-deprecation-rules/issues/76

**Closed as completed by ondrejmirtes** 2022-10-31 13:31 UTC
